[project]
name = "simpleSurvey"
version = "0.0.1"
description = "BlueOS Simple ping ssurvey"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests",
    "flask",
]

